server:
  port: 8080
  servlet:
    context-path: /api
spring:
  application:
    name: Products
  datasource:
    url: jdbc:postgresql://localhost:5432/ads_products
    username: postgres
    password: postdba
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true